version: '3.8'
services:
 db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - /Users/sougulat1/Downloads/komal/data-sdet/test-env/db-env/psql_data/infile:/infile
      - pg_data:/var/lib/postgresql/data/
volumes:
  pg_data:
